
spring: 
  profiles: 
    active:
      - dev
---

spring:
  profiles: dev
    application:
      name: SpringCloudConfigDemo-dev

---

spring:
  profiles: test
    application:
      name: SpringCloudConfigDemo-test






